apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-creator
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["create", "get", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-creator-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: repcal
roleRef:
  kind: ClusterRole
  name: cronjob-creator
  apiGroup: rbac.authorization.k8s.io
